# Generated by Django 2.0 on 2017-12-12 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images_url', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MVinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True)),
                ('url', models.CharField(max_length=255)),
                ('second_type', models.CharField(max_length=16)),
                ('cover_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='four.ImagesUrl', to_field='images_url')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typee', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='mvinfo',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='four.Type', to_field='typee'),
        ),
    ]
