# Generated by Django 2.0 on 2017-12-12 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('four', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mvinfo',
            name='cover_url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='four.ImagesUrl'),
        ),
        migrations.AlterField(
            model_name='mvinfo',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='four.Type'),
        ),
    ]
